### ISSUE TITLE
[Bug] Running `npm install` after unzipping 

### ISSUE THREAD

**Issue by jamesobrooks** [creativetimofficial/ct-soft-ui-design-system-pro#30]
### Version
1.0.9
### Reproduction link
https://github.com/creativetimofficial/ct-soft-ui-design-system-pro
### Operating System
Windows [Version 10.0.19044.1645]
### Device
Dell
### Browser & Version
n/a
### Steps to reproduce
1. Unzip archive
2. `cd` into `soft-ui-design-system-pro-html-v1.0.9` directory
3. Run `npm install`
4. Run `npm start`
### What is expected?
`npm start` should successfully start the application.
### What is actually happening?
The script exits with status code 1. The following is the terminal output.
```
C:\Repos\soft-ui\soft-ui-design-system-pro-html-v1.0.9>npm start

> soft-ui-design-system-pro@1.0.9 start C:\Repos\soft-ui\soft-ui-design-system-pro-html-v1.0.9
> npm run open-app


> soft-ui-design-system-pro@1.0.9 open-app C:\Repos\soft-ui\soft-ui-design-system-pro-html-v1.0.9
> gulp open-app

Error: Cannot find module 'sass'
Require stack:
- C:\Repos\soft-ui\soft-ui-design-system-pro-html-v1.0.9\gulpfile.js
- C:\Repos\soft-ui\soft-ui-design-system-pro-html-v1.0.9\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js
- C:\Repos\soft-ui\soft-ui-design-system-pro-html-v1.0.9\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js
- C:\Repos\soft-ui\soft-ui-design-system-pro-html-v1.0.9\node_modules\gulp\node_modules\gulp-cli\index.js
- C:\Repos\soft-ui\soft-ui-design-system-pro-html-v1.0.9\node_modules\gulp\bin\gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\Repos\soft-ui\soft-ui-design-system-pro-html-v1.0.9\gulpfile.js:3:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Repos\\soft-ui\\soft-ui-design-system-pro-html-v1.0.9\\gulpfile.js',
    'C:\\Repos\\soft-ui\\soft-ui-design-system-pro-html-v1.0.9\\node_modules\\gulp\\node_modules\\gulp-cli\\lib\\shared\\require-or-import.js',
    'C:\\Repos\\soft-ui\\soft-ui-design-system-pro-html-v1.0.9\\node_modules\\gulp\\node_modules\\gulp-cli\\lib\\versioned\\^4.0.0\\index.js',
    'C:\\Repos\\soft-ui\\soft-ui-design-system-pro-html-v1.0.9\\node_modules\\gulp\\node_modules\\gulp-cli\\index.js',
    'C:\\Repos\\soft-ui\\soft-ui-design-system-pro-html-v1.0.9\\node_modules\\gulp\\bin\\gulp.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! soft-ui-design-system-pro@1.0.9 open-app: `gulp open-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the soft-ui-design-system-pro@1.0.9 open-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\james\AppData\Roaming\npm-cache\_logs\2022-05-11T02_25_19_645Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! soft-ui-design-system-pro@1.0.9 start: `npm run open-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the soft-ui-design-system-pro@1.0.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\james\AppData\Roaming\npm-cache\_logs\2022-05-11T02_25_19_686Z-debug.log
```

---

**Comment by groovemen** [comment]
Hello @jamesobrooks,

Thank you for using our products and for letting us know about this issue. Until the next product update, we'll ask you to make the following change:
- go to `package.json` and replace the **devDependencies** with the following ones:
 ```
"devDependencies": {
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^7.0.1",
    "gulp-clean": "^0.4.0",
    "gulp-install": "^1.1.0",
    "gulp-sass": "^5.1.0",
    "gulp-sourcemaps": "^2.6.5",
    "gulp-open": "^3.0.1",
    "sass": "^1.49.9"
  },
```
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by jamesobrooks** [comment]
@groovemen,

Thanks! That worked well, and I think actually fixed another strange issue I was having. I was previously getting errors even running `npm i` from GitBash and had to use Windows' built-in command prompt. Now I can run everything from GitBash as usual.

**Comment by groovemen** [comment]
Hello again,

That's great! Good to hear that.

Cheers,
 Stefan
